### ISSUE TITLE
Add configuration for Traxxas Slash 4x4 Platinum (C1T vehicle)

### ISSUE THREAD

**Issue by adamlm** [usdot-fhwa-stol/carma-config#119]
### Types of Issue

- [ ] Anomaly report (something appears to not work correctly)
- [x] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary

In order to deploy CARMA (or a subset) to a C1T vehicle in the same manner as a full vehicle, we need a configuration specific to the C1T vehicle.

### Carma version where this issue was discovered

N/A

### Expected behavior
We have a configuration for the C1T vehicle.

### Actual behavior

We don't have a configuration for the C1T vehicle

### Steps to reproduce the actual behavior

N/A

**Comment by msmcconnell** [comment]
Resolved by above PR
